# Generated by Django 3.0.13 on 2021-04-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200)),
                ('productPrice', models.IntegerField()),
                ('productBrand', models.CharField(max_length=200)),
                ('productCategory', models.TextField()),
            ],
        ),
    ]
