# Generated by Django 3.0.13 on 2021-04-05 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productBrand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productCategory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productPrice',
        ),
    ]
