# Generated by Django 3.0.14 on 2021-04-13 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='username',
            new_name='username1',
        ),
    ]
