# Generated by Django 3.0.14 on 2021-04-13 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_auto_20210413_0643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='username1',
            new_name='username',
        ),
    ]
