# Generated by Django 3.0.14 on 2021-04-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_auto_20210423_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Vegetable', 'Vegetable'), ('Fruit', 'Fruit'), ('Meat', 'Meat'), ('Pantry', 'Pantry'), ('Dairy', 'Dairy'), ('Frozen Foods', 'Frozen Foods')], max_length=200, null=True),
        ),
    ]
