# Generated by Django 3.0.14 on 2021-04-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_auto_20210413_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_customer',
            field=models.BooleanField(default=True),
        ),
    ]
