# Generated by Django 3.0.14 on 2021-04-14 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_customer_is_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='RANDOM1234',
        ),
    ]
