# Generated by Django 3.0.13 on 2021-04-05 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_auto_20210405_0228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
