# Generated by Django 3.0.14 on 2021-04-14 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0005_auto_20210414_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='RANDOM1234',
            new_name='price',
        ),
    ]
