# Generated by Django 3.0.14 on 2021-04-24 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0006_auto_20210424_1752'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderedItems',
            new_name='OrderedItem',
        ),
        migrations.AlterModelOptions(
            name='ordereditem',
            options={'verbose_name': 'Ordered Item'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
