# Generated by Django 3.0.14 on 2021-04-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0006_auto_20210414_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Vegetable', 'Vegetable'), ('Fruit', 'Fruit'), ('Meat', 'Meat'), ('Pantry', 'Pantry'), ('Dairy', 'Dairy')], max_length=200, null=True),
        ),
    ]
