# Generated by Django 3.0.14 on 2021-04-09 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0006_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
