# Generated by Django 3.0.14 on 2021-04-16 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0005_auto_20210415_1041'),
        ('web_app', '0007_auto_20210415_0533'),
    ]

    operations = [
    ]
