# Generated by Django 3.0.14 on 2021-04-25 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0008_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
