# Generated by Django 3.0.14 on 2021-04-16 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0008_merge_20210416_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
