# Generated by Django 3.0.14 on 2021-04-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0009_remove_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='yoyoyo/'),
        ),
    ]
