# Generated by Django 3.0.14 on 2021-04-29 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0011_auto_20210425_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Vegetable', 'Vegetable'), ('Fruit', 'Fruit'), ('Meat', 'Meat'), ('Pantry', 'Pantry'), ('Dairy', 'Dairy'), ('Frozen Foods', 'Frozen Foods'), ('Beverage', 'Beverage')], max_length=200, null=True),
        ),
    ]
