# Generated by Django 3.0.14 on 2021-04-29 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0012_auto_20210428_2352'),
        ('web_app', '0012_auto_20210429_0014'),
    ]

    operations = [
    ]
