# Generated by Django 3.0.14 on 2021-04-29 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0014_product_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='amount',
            new_name='amount_in_stock',
        ),
    ]
