# Generated by Django 3.0.14 on 2021-05-06 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0021_auto_20210505_2349'),
        ('web_app', '0023_auto_20210506_0017'),
        ('web_app', '0021_auto_20210505_2341'),
    ]

    operations = [
    ]
