# Generated by Django 3.0.14 on 2021-05-06 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0021_auto_20210505_2349'),
        ('web_app', '0024_merge_20210506_0059'),
    ]

    operations = [
    ]
