# Generated by Django 3.0.14 on 2021-05-06 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0025_auto_20210506_0552'),
        ('web_app', '0025_merge_20210506_0314'),
    ]

    operations = [
    ]
