# Generated by Django 3.0.14 on 2021-05-07 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0026_merge_20210506_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
