# Generated by Django 3.0.14 on 2021-05-07 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0027_auto_20210507_0028'),
        ('web_app', '0027_auto_20210507_0006'),
    ]

    operations = [
    ]
