# Generated by Django 3.0.14 on 2021-05-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0033_auto_20210508_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_status',
        ),
        migrations.AddField(
            model_name='order',
            name='checkout',
            field=models.CharField(choices=[('Complete', 'Complete')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], max_length=200, null=True),
        ),
    ]
