# Generated by Django 3.0.14 on 2021-05-10 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0036_auto_20210509_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
