# Generated by Django 3.0.14 on 2021-05-12 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0039_auto_20210512_0012'),
        ('web_app', '0039_auto_20210512_0217'),
    ]

    operations = [
    ]
