# Generated by Django 3.0.14 on 2021-05-12 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0040_merge_20210512_0529'),
        ('web_app', '0028_merge_20210507_0329'),
    ]

    operations = [
    ]
