# Generated by Django 3.0.14 on 2021-05-13 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0041_merge_20210512_1732'),
        ('web_app', '0041_auto_20210513_0113'),
    ]

    operations = [
    ]
