# Generated by Django 3.0.14 on 2021-05-13 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0045_auto_20210513_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
