# Generated by Django 3.0.14 on 2021-05-13 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0047_auto_20210513_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('Uninitialized', 'Uninitialized'), ('Received', 'Received')], default='Uninitialized', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping',
            field=models.CharField(choices=[('Uninitialized', 'Uninitialized'), ('Out for delivery', 'Out for delivery')], default='Uninitialized', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('None', 'None'), ('Pending', 'Pending'), ('Approved', 'Approved')], default='None', max_length=200, null=True),
        ),
    ]
